backend:
  name: git-gateway
  branch: master

media_folder: "static/upload"
public_folder: "upload"

collections:
  - name: "cars"
    label: "car"
    folder: "content/cars"
    filter:
    field: language
    value: en
    create: true
    fields:
      - {label: "Language", name: "language"}
