backend:
  name: git-gateway
  branch: master

media_folder: "static/upload"
public_folder: "upload"

collections:
  - name: "post"
    label: "post"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{slug}}"

    