backend:
  name: git-gateway
  branch: master

media_folder: "static/upload"
public_folder: "upload"

collections:
  - name: "cars"
    label: "cars"
    folder: "content/cars"
    filter:
      field: language
      value: en
    fields:
      - {label: "Language", name: "language"}
